# Generated by Django 3.2.8 on 2021-10-15 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReason',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(blank=True, max_length=9, null=True)),
                ('content', models.CharField(max_length=1024)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.messagereason')),
            ],
        ),
    ]
