# Generated by Django 3.2.8 on 2021-10-09 22:41

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerAZ',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('button_content', models.CharField(default='["A",]', max_length=256)),
                ('correct', models.CharField(default='A', max_length=1)),
                ('points', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerAZWithContent',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('button_content', models.CharField(default='["A",]', max_length=256)),
                ('content', models.TextField()),
                ('correct', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerTrueFalse',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('correct', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerWithContent',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('correct', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=False, null=True, quality=75, size=[1920, 1080], upload_to='./static/img/question/')),
                ('audio', models.FileField(null=True, upload_to='./static/audio/')),
                ('year', models.IntegerField()),
                ('explanation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maturaguideapi.explanation')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maturaguideapi.subject')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerCategory',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maturaguideapi.subject')),
            ],
        ),
    ]
