# Generated by Django 3.2.8 on 2021-10-10 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maturaguideapi', '0004_alter_explanation_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeraz',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maturaguideapi.question'),
        ),
        migrations.AddField(
            model_name='answerazwithcontent',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maturaguideapi.question'),
        ),
        migrations.AddField(
            model_name='answertruefalse',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maturaguideapi.question'),
        ),
        migrations.AddField(
            model_name='answerwithcontent',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maturaguideapi.question'),
        ),
        migrations.AlterField(
            model_name='answerazwithcontent',
            name='correct',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
