# Generated by Django 3.2.8 on 2021-10-10 10:38

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('maturaguideapi', '0005_auto_20211010_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerwithcontent',
            name='buttons_content',
            field=models.JSONField(default=list, help_text='Teksty które będą pojawiały się koło przycisków.'),
        ),
        migrations.AlterField(
            model_name='answeraz',
            name='button_content',
            field=models.JSONField(default=list, help_text='Zawartość przycisków w JSON.', max_length=256),
        ),
        migrations.AlterField(
            model_name='answeraz',
            name='correct',
            field=models.CharField(default='A', help_text='Zawartość prawidłowego buttona.', max_length=1),
        ),
        migrations.AlterField(
            model_name='answeraz',
            name='points',
            field=models.IntegerField(default=1, help_text='Punkty które użytkownik dostaje za poprawną odpowiedź.'),
        ),
        migrations.AlterField(
            model_name='answeraz',
            name='question',
            field=models.ForeignKey(help_text='Połączenie z pytaniem.', null=True, on_delete=django.db.models.deletion.CASCADE, to='maturaguideapi.question'),
        ),
        migrations.AlterField(
            model_name='answerazwithcontent',
            name='button_content',
            field=models.JSONField(default=list, help_text='Zawartość przycisków w JSON.', max_length=256),
        ),
        migrations.AlterField(
            model_name='answerazwithcontent',
            name='content',
            field=models.TextField(help_text='Zawartość pytania.'),
        ),
        migrations.AlterField(
            model_name='answerazwithcontent',
            name='correct',
            field=models.CharField(default='A', help_text='Zawartość prawidłowego buttona.', max_length=1),
        ),
        migrations.AlterField(
            model_name='answerazwithcontent',
            name='points',
            field=models.IntegerField(default=1, help_text='Punkty które użytkownik dostaje za poprawną odpowiedź.'),
        ),
        migrations.AlterField(
            model_name='answerazwithcontent',
            name='question',
            field=models.ForeignKey(help_text='Połączenie z pytaniem.', null=True, on_delete=django.db.models.deletion.CASCADE, to='maturaguideapi.question'),
        ),
        migrations.AlterField(
            model_name='answertruefalse',
            name='content',
            field=models.TextField(help_text='Zawartość pytania.'),
        ),
        migrations.AlterField(
            model_name='answertruefalse',
            name='correct',
            field=models.BooleanField(default=False, help_text='Ktore pytanie jest poprawne? Jeżeli checkbox jest zaznaczony to prawidłowa jest prawda.'),
        ),
        migrations.AlterField(
            model_name='answertruefalse',
            name='points',
            field=models.IntegerField(default=1, help_text='Punkty które użytkownik dostaje za poprawną odpowiedź.'),
        ),
        migrations.AlterField(
            model_name='answertruefalse',
            name='question',
            field=models.ForeignKey(help_text='Połączenie z pytaniem.', null=True, on_delete=django.db.models.deletion.CASCADE, to='maturaguideapi.question'),
        ),
        migrations.AlterField(
            model_name='answerwithcontent',
            name='correct',
            field=models.IntegerField(default=False, help_text='Indeks poprawnej odpowiedzi.'),
        ),
        migrations.AlterField(
            model_name='answerwithcontent',
            name='points',
            field=models.IntegerField(default=1, help_text='Punkty które użytkownik dostaje za poprawną odpowiedź.'),
        ),
        migrations.AlterField(
            model_name='answerwithcontent',
            name='question',
            field=models.ForeignKey(help_text='Połączenie z pytaniem.', null=True, on_delete=django.db.models.deletion.CASCADE, to='maturaguideapi.question'),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='content',
            field=models.JSONField(default=list, help_text='Wyjasnienia do zadań w postaci listy.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, help_text='Plik dźwiękowy do zadania, jeżeli null to pytanie nie będzie miało nagrania.', null=True, upload_to='./static/audio/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(help_text='Zawartość zadania.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.ForeignKey(help_text='Połączenie z wyjaśnieniami.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='maturaguideapi.explanation'),
        ),
        migrations.AlterField(
            model_name='question',
            name='header',
            field=models.TextField(help_text='Poczatek zadania który będzie wyświetlony grubą czcionką.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='Dodatkowy obrazek do zadania, jeżeli null to pytanie nie będzie miało obrazu.', keep_meta=False, null=True, quality=75, size=[1920, 1080], upload_to='./static/img/question/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(help_text='Przedmiot', on_delete=django.db.models.deletion.CASCADE, to='maturaguideapi.subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='year',
            field=models.IntegerField(help_text='Rok w którym pytanie pojawiło się na egzaminie maturalnym.'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Nazwa przedmiotu np. Matematyka', max_length=128),
        ),
    ]
