# Generated by Django 3.2.8 on 2021-10-10 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maturaguideapi', '0006_auto_20211010_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.ForeignKey(blank=True, help_text='Połączenie z wyjaśnieniami.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='maturaguideapi.explanation'),
        ),
    ]
