# Generated by Django 3.2.8 on 2021-10-10 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maturaguideapi', '0007_alter_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_category',
            field=models.ForeignKey(help_text='Kategoria pytania.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='maturaguideapi.questioncategory'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_tags',
            field=models.ManyToManyField(help_text='Tagi pytania.', null=True, to='maturaguideapi.QuestionTag'),
        ),
    ]
