# Generated by Django 3.2.8 on 2021-10-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturaguideapi', '0009_alter_question_question_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeraz',
            name='button_content',
        ),
        migrations.RemoveField(
            model_name='answerazwithcontent',
            name='button_content',
        ),
        migrations.AddField(
            model_name='answeraz',
            name='buttons_content',
            field=models.JSONField(default=list, help_text='Zawartość przycisków w JSON.', max_length=256),
        ),
        migrations.AddField(
            model_name='answerazwithcontent',
            name='buttons_content',
            field=models.JSONField(default=list, help_text='Zawartość przycisków w JSON.', max_length=256),
        ),
        migrations.AddField(
            model_name='question',
            name='cke_order',
            field=models.IntegerField(blank=True, help_text='Numer zadania w arkuszu cke (jeżeli null to znaczy że zadanie nie pochodzi z arkusza CKE)', null=True),
        ),
    ]
