# Generated by Django 3.2.8 on 2021-10-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturaguideapi', '0010_auto_20211010_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
        migrations.AddField(
            model_name='answeraz',
            name='explanation',
            field=models.TextField(blank=True, help_text='Wyjaśnienie do pytania', null=True),
        ),
        migrations.AddField(
            model_name='answerazwithcontent',
            name='explanation',
            field=models.TextField(blank=True, help_text='Wyjaśnienie do pytania', null=True),
        ),
        migrations.AddField(
            model_name='answertruefalse',
            name='explanation',
            field=models.TextField(blank=True, help_text='Wyjaśnienie do pytania', null=True),
        ),
        migrations.AddField(
            model_name='answerwithcontent',
            name='explanation',
            field=models.TextField(blank=True, help_text='Wyjaśnienie do pytania', null=True),
        ),
    ]
