# Generated by Django 3.2.8 on 2021-10-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturaguideapi', '0011_auto_20211010_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioncategory',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='questiontag',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(default='Podstawowe', help_text='Typ przedmiotu rozserzony, podstawowy', max_length=20),
            preserve_default=False,
        ),
    ]
