# Generated by Django 3.2.8 on 2021-10-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturaguideapi', '0012_auto_20211012_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('P', 'Podstawowy'), ('R', 'Rozserzony')], help_text='Typ przedmiotu rozserzony, podstawowy', max_length=1),
        ),
    ]
