# Generated by Django 3.2.8 on 2021-10-14 20:47

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('maturaguideapi', '0013_alter_subject_subject_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.SmallIntegerField(choices=[(1, 'Prawda, fałsz'), (2, 'Przyciski od A - Z'), (3, 'Przyciski z zawartością')])),
                ('button_content', models.JSONField(blank=True, default=list, null=True)),
                ('content', models.CharField(blank=True, max_length=512, null=True)),
                ('to_button', models.CharField(blank=True, default='Z', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Excercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('audio', models.FileField(blank=True, help_text='Plik dźwiękowy do zadania, jeżeli null to pytanie nie będzie miało nagrania.', null=True, upload_to='./static/audio/')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='Dodatkowy obrazek do zadania, jeżeli null to pytanie nie będzie miało obrazu.', keep_meta=False, null=True, quality=75, size=[1920, 1080], upload_to='./static/img/question/')),
                ('header', models.TextField(default=None, null=True)),
                ('content', models.TextField(default=None, null=True)),
                ('footer', models.TextField(default=None, null=True)),
                ('more_text', models.TextField(default=None, null=True)),
                ('correct', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StudySource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='answerazwithcontent',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answertruefalse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answerwithcontent',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='question',
            name='header',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_tags',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='question',
            name='year',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='maturaguideapi.questioncategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='cke_year',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='maturaguideapi.subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='explanation',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='cke_order',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='AnswerAZ',
        ),
        migrations.DeleteModel(
            name='AnswerAZWithContent',
        ),
        migrations.DeleteModel(
            name='AnswerTrueFalse',
        ),
        migrations.DeleteModel(
            name='AnswerWithContent',
        ),
        migrations.DeleteModel(
            name='QuestionTag',
        ),
        migrations.AddField(
            model_name='excercise',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maturaguideapi.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='excercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maturaguideapi.excercise'),
        ),
        migrations.AddField(
            model_name='answer',
            name='explanation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maturaguideapi.explanation'),
        ),
    ]
