# Generated by Django 3.2.8 on 2021-10-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturaguideapi', '0014_auto_20211014_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioncategory',
            name='subject',
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='subject',
            field=models.ManyToManyField(to='maturaguideapi.Subject'),
        ),
    ]
