# Generated by Django 3.2.8 on 2021-10-14 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maturaguideapi', '0015_auto_20211014_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='maturaguideapi.subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='cke_order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='cke_year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
