# Generated by Django 3.2.8 on 2021-10-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturaguideapi', '0016_auto_20211014_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excercise',
            name='correct',
        ),
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
