# Generated by Django 3.2.8 on 2021-10-14 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maturaguideapi', '0017_auto_20211014_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='explanation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maturaguideapi.explanation'),
        ),
    ]
