# Generated by Django 3.2.8 on 2021-10-14 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maturaguideapi', '0018_alter_answer_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excercise',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='excercise',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='maturaguideapi.excercise'),
            preserve_default=False,
        ),
    ]
