# Generated by Django 3.2.8 on 2021-10-14 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maturaguideapi', '0019_auto_20211014_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='excercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maturaguideapi.excercise'),
        ),
    ]
