# Generated by Django 3.2.8 on 2021-10-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturaguideapi', '0020_alter_question_excercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excercise',
            name='content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='excercise',
            name='footer',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='excercise',
            name='header',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='excercise',
            name='more_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
