# Generated by Django 3.2.8 on 2021-10-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturaguideapi', '0023_auto_20211019_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='footer',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='header',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_type',
            field=models.SmallIntegerField(choices=[(1, 'Prawda, fałsz'), (2, 'Przyciski od A - Z'), (3, 'Przyciski z zawartością'), (4, 'Tekst z przyciskami A - Z')]),
        ),
    ]
