# Generated by Django 3.2.8 on 2021-10-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturaguideapi', '0024_auto_20211020_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='context_text',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
