# Generated by Django 3.2.8 on 2021-10-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maturaguideapi', '0025_answer_context_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='content',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='context_text',
        ),
    ]
