# Generated by Django 3.2.8 on 2021-10-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturaguideapi', '0026_auto_20211020_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
