# Generated by Django 3.2.8 on 2021-10-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maturaguideapi', '0027_answer_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='header',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='title',
        ),
    ]
