# Generated by Django 3.2.8 on 2021-10-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturaguideapi', '0029_answer_more_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysource',
            name='title',
        ),
        migrations.AddField(
            model_name='excercise',
            name='study_sources',
            field=models.ManyToManyField(to='maturaguideapi.StudySource'),
        ),
        migrations.AddField(
            model_name='studysource',
            name='description',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
